Repository robrbecker/experiment, pull requests merged in 2022-04, with the labels that each got.

#16 Update README.md
  README.md
Labels: semver:patch

#17 Update README.md
  README.md
Labels: semver:major

#18 Update README.md
  README.md
Labels: semver:patch

#19 Update README.md
  README.md
Labels: semver:patch, unreleased

#20 Update README.md
  README.md
Labels: semver:patch, unreleased

#21 Update generated.txt
  generated.txt
Labels: semver:minor, unreleased

#22 Update README.md
  README.md
Labels: semver:patch, no_release_on_merge, unreleased
